# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean")
    gradle(task: "assemble",
        build_type: "DevRelease")
   # gradle(task: "crashlyticsUploadDistributionDevRelease")
     crashlytics(
       api_token: 'a8b41b25dd79710d84ecc62b36dba9131b7f3d06',
       build_secret: '1f1f01a6fb84ca1644b2b0be2db6f4312daed7aad9f393e1dc056106b77db34e',
     )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

#  desc "Deploy a new version to the Google Play"
#  lane :deploy do
#    gradle(task: "clean assembleRelease")
#    upload_to_play_store
#  end
end
